### ISSUE TITLE
Can't build invalid html

### ISSUE THREAD

**Issue by AParks** [ZengineHQ/mayan#12]
I ran into an issue trying to build the html for bulk email and got the following output:
```
mayan build --frontend

Building frontend bulk-email/788
 ✔ Running pre-build scripts
 ✔ Installing node_modules
 ✔ Installing dependencies
 ✔ Building Javascript files
 ✔ Building SCSS/CSS files
 ✖ Building HTML files
   → </script>
   Running post-build scripts
   Cleaning up
mayan build [plugin]

Build plugin

Positionals:
  plugin  Plugin name                                    [string] [default: "*"]

Options:
  --env          Environment name
  --help         Show help                                             [boolean]
  --show-hidden  Show advanced options                                 [boolean]
  --frontend     Only build frontend plugins          [boolean] [default: false]
  --backend      Only build backend services          [boolean] [default: false]

TypeError: Cannot convert object to primitive value
    at PluginError._messageDetails (/Users/parksa/Documents/zengine/plugins/mayan/node_modules/gulp-htmlmin/node_modules/plugin-error/index.js:102:24)
    at PluginError._messageWithDetails (/Users/parksa/Documents/zengine/plugins/mayan/node_modules/gulp-htmlmin/node_modules/plugin-error/index.js:81:22)
    at PluginError.toString (/Users/parksa/Documents/zengine/plugins/mayan/node_modules/gulp-htmlmin/node_modules/plugin-error/index.js:133:14)
    at new Error (<anonymous>)
    at promise.then.catch.err (/Users/parksa/Documents/zengine/plugins/mayan/lib/util.js:78:13)
    at <anonymous>
```

This is because of the minification step; the gulp plugin uses this [minifier](https://github.com/kangax/html-minifier#working-with-invalid-markup), which as they say in the README:
> HTMLMinifier can't work with invalid or partial chunks of markup.

I was able to modify the mayan source locally to skip the minification process so it would generate the `plugin.html` file, and got lucky and found the invalid closing tag at the very end of the file. However, this isn't always the case, so I could imagine it normally being pretty hard to debug where the issue is without more verbose output. The same complaint is brought up [here](https://github.com/kangax/html-minifier/issues/695#issuecomment-235383928), and the suggestion is to use the [HTML linter](https://github.com/kangax/html-lint) that used to be part of the minifier.

**Comment by alexweber** [comment]
@AParks nice find!  I think we should also add a `--skip-minify` or `--skip-compress` or something option to the build task as a bonus

**Comment by tedkulp** [comment]
Safe to close this now that `--skip-minify` is a thing?
