### ISSUE TITLE
Improve error handling for deploy/publish commands

### ISSUE THREAD

**Issue by evert0n** [ZengineHQ/mayan#14]
Error handling for deploy/publish isn't finished currently it's just throw and exits

Example when an invalid token is used:

```
Error: Error: Error: StatusCodeError: 401 - {"error":"invalid_grant","error_description":"The access token provided has expired"}
    at promise.then.catch.err (/Users/everton/Projects/mayan/lib/util.js:78:13)
    at <anonymous>

```
Working on this one

**Comment by tehpsalmist** [comment]
@evert0n Did I just file a duplicate issue, or are [my concerns](https://github.com/ZengineHQ/mayan/issues/15) separate than what you're working on in this one?

**Comment by evert0n** [comment]
@tehpsalmist I think this is different addressing specifically http requests to the Zengine API and other errors that can possible happens in deploy/publish steps

**Comment by tehpsalmist** [comment]
@evert0n How is this looking? Are we handling errors up-to-par at this point?

**Comment by evert0n** [comment]
@tehpsalmist see PR #34

**Comment by evert0n** [comment]
It's partially improved needs more work, eg #5 needs to be worked
