### ISSUE TITLE
Build Error dirtying up my workspace with all manner of files

### ISSUE THREAD

**Issue by tehpsalmist** [ZengineHQ/mayan#15]
When the build process errors out, it would be nice if the cleanup functions could still run and clear out all that stuff. Maybe some would want that for debugging purposes, but I would rather they just be gone.

**Comment by alexweber** [comment]
@tehpsalmist by "all manner of files" do you just mean files in the `/build` folder?

These should be in the standard gitignore and shouldn't really be an issue but there might be a case for cleaning up after errors occur.... although the debris could be helpful.... 

@evert0n @AParks thoughts?

**Comment by alexweber** [comment]
The more I think about this one I think that any temporary files we need to create during the build process should live in the top level `./maya_build` in a `temp` or something directory... that way even though these files are meant to be short-lived they will be even less distracting
