### ISSUE TITLE
implement a `--skip-minify` flag for the build command

### ISSUE THREAD

**Issue by alexweber** [ZengineHQ/mayan#17]
related to #12

**Comment by AParks** [comment]
does this actually work? I looks like it still calls htmlmin, even if you pass skip-minify, just with fewer options. When I was testing this locally it *was* already not a prod env, and it was still failing.

**Comment by alexweber** [comment]
@AParks yeah it works, what do you mean it was failing?  I didn't fix the issue related to the HTML linting, that's your baby :)    As far as I can tell calling htmlmin without params doesnt do much, on a plugin here im getting -200 lines of HTML in production mode so its doing something... i suppose we can make it not call htmlmin at all in non prod to avoid confusion

**Comment by alexweber** [comment]
@AParks ^

**Comment by AParks** [comment]
yea I had some invalid html in there, so the whole build was failing. Now, thanks to this change, you can pass this `skip-minify` flag as an easy workaround to getting your plugin deployed.
