### ISSUE TITLE
Backup command

### ISSUE THREAD

**Issue by evert0n** [ZengineHQ/mayan#22]
A couple of times now, I had to do a backup of the current deployed plugin (to be able to rollback if needed)
Would be helpful if mayan could do that backup for me in a single command line

Most time I want to do it is when a plugin is deployed to production but hasn't been previous managed by Git or maya/mayan

**Comment by tehpsalmist** [comment]
Essentially we have this capability (for non-git projects) with the [zengine-migrator's](https://github.com/ZengineHQ/zengine-migrator) `-i -t` flags. Everything else is managed by git. Good work team.
