### ISSUE TITLE
allow picking backend services in commands

### ISSUE THREAD

**Issue by alexweber** [ZengineHQ/mayan#27]
currently when processing backend services we're always doing all of them and this can be a nuisance when you have multiple services are only working on one...

Suggested by @wdmny

**Comment by evert0n** [comment]
We have to test this but I thought can could already do `--backend=<service name>` as well `--frontend=<name>`

**Comment by tehpsalmist** [comment]
This is coming with the pelican PR. `--services` or `-s` and it accepts an array of service config names

**Comment by tehpsalmist** [comment]
feature landed a while ago. Noice!
