### ISSUE TITLE
investigate backend symlinks and related concerns/restrict watch to frontend?

### ISSUE THREAD

**Issue by tehpsalmist** [ZengineHQ/mayan#29]
Hey @alexweber , we talked about backend symlinks, and it's occuring to me that nodemon is actually handling them for us (sorry I don't have a specific link, it was a conclusion I drew from a bunch of random SO posts and github issues, as well as my recollection that I relied on this a couple months ago without even thinking about it to make a PR to our backend helper modules). That means no changes are necessary in the backend, and it also means a backend watch command really won't be as good as what nodemon can already do for us.

I am thinking out loud here, but maybe it would be more "user friendly" to just know that the `watch` command is a frontend aid, and the backend services are best run with nodemon. Perhaps we could/should remove the `--frontend` flag (because it would be assumed/implied always) for simplicity (`watch --backend` doesn't work at the moment any way)?

**Comment by alexweber** [comment]
@tehpsalmist great points... now how about if watch `--backend` spun up nodemon for ya?  just off the top :)

**Comment by tehpsalmist** [comment]
Yeah, that's an option, but it still means more typing involved in both commands, and I hate typing.

**Comment by tehpsalmist** [comment]
Concerning backend symlinks, I did some testing, and they do work with nodemon out of the box, with one caveat:

Most of our helper modules are wrappers around a module available in the `backend/{pluginName}/lib` directory, and they require those modules with `../../../lib/package`, so when doing local development, those paths have to be changed, since the relative path between the files will not be the same when it is symlinked. It's not a huge inconvenience, but if anyone knows of a workaround for that, that would be interesting.

**Comment by tehpsalmist** [comment]
This is resolved with the current backend watcher. Well done team.
