### ISSUE TITLE
Add check step for commands

### ISSUE THREAD

**Issue by evert0n** [ZengineHQ/mayan#33]
Some of the messages are a bit hard to understand the issues it represents, for example if you have a wrong plugin path configured on `maya.json` and try to deploy it will error with this message

```
File not found with singular glob: /Users/everton/Projects/zn-plugin-mayan-test/plugins/dummy-frontend-plugin/plugin-register.js (if this was purposeful, use `allowEmpty` option)
```

Would be better to have a check step to error with a more straight forward error message

In this example saying that the frontend plugin doesn't exists

**Comment by tehpsalmist** [comment]
By check step, do you mean a sort of higher-order error handler that will essentially translate error messages into a human-readable format?

**Comment by evert0n** [comment]
No I'm thinking of a task that runs before the others to check pre requisites

**Comment by tehpsalmist** [comment]
Gotcha, that makes sense. I guess it would have to parse the commands and then run an assessment based off of what commands need to be executed, right?

**Comment by evert0n** [comment]
Yeap! I can provide more info if you want to

**Comment by tehpsalmist** [comment]
Sure, let's load this issue up with documentation so we can run with it when the time is right. 👍 🚀

**Comment by tehpsalmist** [comment]
I'd say we've got decent enough error handling at this point. The only thing that is a little awkward is logging the response object for errors, but at least the info is there right now. I don't think we are missing info or providing ambiguous error messaging. If we run up against this kind of problem we can open a new issue.
