### ISSUE TITLE
nvmrc version

### ISSUE THREAD

**Issue by wdmny** [ZengineHQ/mayan#37]
Version should be the latest stable version - 8.10.0. The current nvmrc version does not support features that are used by the app - specifically fs.readFileSync.

**Comment by tehpsalmist** [comment]
Isn't this just running in your local node environment? And doesn't that fs method go back to 0.1.8? Also, since the nvmrc says `v8`, wouldn't that mean the most recent stable release of major version 8?

**Comment by wdmny** [comment]
This came up because David was on v8.0 and maya build was failing.

**Comment by tehpsalmist** [comment]
I think I'm a little unclear on what the solution would be then. It seems like it should work fine even on 8.0, but I don't think I understand what the specific problem is.
