### ISSUE TITLE
Investigate Babel runtime / plugin-transform-runtime

### ISSUE THREAD

**Issue by JoeBello** [ZengineHQ/mayan#41]
In order to support features such as generators and async/await, Zengine plugins will need to include Babel's runtime and plugin-transform-runtime plugins. Mayan would also need to be able to determine which Zengine plugins would require these dependencies based on implementation.

Resources:
[gulp-babel plugin](https://www.npmjs.com/package/gulp-babel)
[@babel/plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime#docsNav)
[@babel/runtime](https://babeljs.io/docs/en/next/babel-runtime.html)

**Comment by tehpsalmist** [comment]
with v2 we have officially landed in the future. well done everyone.
