### ISSUE TITLE
UI overhaul

### ISSUE THREAD

**Issue by alexweber** [ZengineHQ/mayan#5]
Hey @AParks I realize this one is a bit of a stretch but humor me for a bit...

So we're using the excellent [Listr](https://github.com/SamVerschueren/listr) module for the frontend and backend build process right.  Along with the functionality that you've already seen in mayan, Listr actually allows you to define sub-tasks which themselves can be Listr objects and also report status for these individual tasks.

Therefore, I think the utopia setup here would be to use Listr for everything, not just building the plugins (notice how the deploy/publish steps are different).

We could then do something like have a main task tree and each task could have its own sub-tasks:
- Build plugins
-- css
-- js
-- html
-- etc
- Deploy plugins
- Publish plugins
- etc

Then the entire interface would be one giant set of Listr tasks reporting progress etc and be really nice and consistent... :)

**Comment by evert0n** [comment]
Not 100% clean to me what's the change in here but I think it should keep the build, deploy, publish code organized in a way that can be called/executed individually

**Comment by evert0n** [comment]
Would help to get a sense/talk before doing it

**Comment by alexweber** [comment]
@evert0n it wouldnt affect that at all, it would be more of a UI improvements when performing multiple tasks

**Comment by tehpsalmist** [comment]
I'll be honest, I'm not sold on the benefit of Listr beyond what we have going on right now. I think the UI is good enough (even particularly informative at this point?), and that this would amount to a rewrite we don't need right now. Feel free to pushback/discuss, but I'm cleaning up issues and this one seemed irrelevant right now.
