### ISSUE TITLE
Cache node modules

### ISSUE THREAD

**Issue by alexweber** [ZengineHQ/mayan#6]
Currently the longest and most annoying steps to wait for in the build process are installing node modules... everything else happens almost instantly...

That's expected because we're nuking the build dir and starting from scratch every time...

Ideally there would be some 3rd party tool to help but it could even be as simple as storing a checksum of the package.json "dependencies" key and if its the same re-use the existing built node modules, if available

**Comment by AParks** [comment]
@alexweber got this out of memory error after trying to build bulk email....

```Annas-MacBook-Pro:bulk-email-plugin parksa$ mayan build

Building frontend bulk-email/788
 ✔ Running pre-build scripts
 ✔ Installing node_modules
 ✔ Installing dependencies
 ⠴ Building Javascript files
   Building SCSS/CSS files
   Building HTML files
   Running post-build scripts
   Cleaning up


#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
Illegal instruction: 4```

Do you think it's related? I.e. ran out of memory to build the JS files after installing all those node modules?

**Comment by tehpsalmist** [comment]
In doing this, it would appear that the backend services don't account for symlinks. Can anyone confirm that is correct? @alexweber ?

**Comment by alexweber** [comment]
@tehpsalmist that's correct

**Comment by tehpsalmist** [comment]
obsolete with all the watching stuff we have going on. Great work team.
