### ISSUE TITLE
pbcopy does not work on windows/linux

### ISSUE THREAD

**Issue by dmcgrathwizehive** [ZengineHQ/mayan#75]
in mayan/lib/backend/watch.js line 86-90 we use pbcopy to copy the ngrok url to the clipboard

```
  const copy = require('child_process').spawn('pbcopy')
  copy.stdin.write(url)
  copy.stdin.end()
  console.log(green(`${italic(url)} --> copied to clipboard!`))
```
this is not available by default on windows.

some potential solutions/workarounds

could catch an error and point users to install:
https://ghuntley.com/blog/pbcopy-pbpaste-for-windows-released

can use windows 'clip' command
https://superuser.com/questions/472598/pbcopy-for-windows

**Comment by AParks** [comment]
Or linux ....

**Comment by chris-p1** [comment]
> Or linux ....
> 
> workaround - https://ostechnix.com/how-to-use-pbcopy-and-pbpaste-commands-on-linux/

This workaround uses `pbcopy` as a shell aliases, which will only work in interactive mode.

I was able to get this working on Linux by doing the following:

Create two shell scripts, one for `pbcopy` and `pbpaste`
`touch pbcopy.sh && touch pbpaste.sh`

Edit the scripts to use either `xclip` or `xsel`, whichever you have.

pbcopy.sh:
`#!/bin/sh

# if using xclip
xclip -selection clipboard

# if using xsel
xsel --clipboard --input
`

pbpaste.sh:
`#!/bin/sh

# if using xclip
xclip -selection clipboard -o

# if using xsel
xsel --clipboard --output
`

Make these scripts executable
`
chmod +x pb*
`

Create a symlink to these scripts in a directory that is in your $PATH, i.e. `~/.local/bin`
`$ ln -s /path/to/your/pbcopy.sh ~/.local/bin/pbcopy
$ ln -s /path/to/your/pbpaste.sh ~/.local/bin/pbpaste
`
